### ISSUE TITLE
No longer works?

### ISSUE THREAD

**Issue by jtwalters** [jamesdotcuff/iFitController#1]
Anyone had success with this on a late model x22i? Doesn't seem like port 80 is open anymore. Any alternative ways to send commands? I was able to connect via `adb` but not sure what all I can do.

**Comment by jamesdotcuff** [comment]
Hi JT, sorry for the delay.  Just revisited this code this evening, and Version 3.4.0324.0.0.5.2.3 firmware on our 2950 still seems to work just fine.  Sorry I don't know about the x22i I'm afraid.  :-(

![Screen Shot 2020-07-29 at 11 31 36 PM](https://user-images.githubusercontent.com/1484037/88877545-bc062980-d1f3-11ea-85d1-ec65611f9da6.png)

**Comment by omriasta** [comment]
I just got a nordictrack commercial 2950 and this isn't working on it. It looks like the only port open on the machine is 5555 which has Android adb listening and you can open a root she'll on it. So port 80 is closed now.

**Comment by cfurrow** [comment]
FYI (not a bug, just adding additional info for other googlers):

Confirmed NOT working on Nordictrack Commercial 2450.

Open ports: 5000, 5009, 5555

None allow for websocket connections at the root path, or at `/control`

**Comment by jamesdotcuff** [comment]
Oops, sorry team Did have a feeling that this little hole would be patched eventually. Looks like we won't be able to let elmo ride again. Be nice if there was a legit API with OAUTH tokens and some level of security.  sigh.  Sorry all!

**Comment by omriasta** [comment]
THere is an api working with oauth but they closed down the site to register an app. I was able to get the client id and secret out of the android phone app.... and it's working but a bit hesitant to publish anything using this info.

**Comment by cfurrow** [comment]
> bit hesitant to publish anything using this info

That seems like a good idea to keep it a secret.

**Comment by omriasta** [comment]
The oauth uses the legacy "password" grant_type. So you still need a user and password. The client_id and client_secret are generic for their android app and is the same for anyone using this app. I'm more hesitant to publish it so they don't change them and I'm sure it violates their TOS. If they didn't want those to get out they should have used a better oauth grant_type. It seems like they used to have an endpoint to register an app but have since closed it off. If you search online there is a post on the fitbit community that shows what used to be available. The api they mention is still working but there is no way to access it unless you pretend to be the android app...

**Comment by jantznick** [comment]
I've heard that NordicTrack commercial units post 2017 aren't capable of doing this anymore. Curious if it works on other ifit devices such as some of the ProForm treadmills

**Comment by Irrelon** [comment]
Can't see how it could violate any TOS that was in any way enforcable. I guess it depends on your region etc but I remember a court case in the US around ownership of devices and usage of their internals for your own use. In the UK it would probably be similar... I cannot see how it could possibly be enforced in the UK since they'd have to prove loss.

On top of that, the client id and secret being extracted from the app would again be acceptable use as far as I can see. The data is running on your network that you own. The app is running on your phone that you own. The treadmill is an item you own.

Speaking of which, did you extract via plugging in your phone and debugging via adb or something, or monitor traffic across your network and inspect the HTTP calls going to the treadmill, or did you extract via the app code itself?

I don't see how any of this could be considered proprietary intelectual property... but I'm not a lawyer! I'm having a chat with a very knowledgeable lawyer this evening so I'll clear this up at least from the UK side of law.

**Comment by omriasta** [comment]
I'm in the US so not sure if your laws would apply here. The client id and secret were extracted using a proxy listening in on the traffic. I just know that it is not meant to be accessible by the company and there may be some legality surrounding accessing info that is not intended to be available. I have published a python script that accesses the API and uploads it to google fit. Remember that my script is not accessing the treadmill but the API on ifits servers.... I have published the script but just hesitant about publishing the client id and client secret. There are enough tutorials online on how to do this using fiddler and genymotion.
